# Generated by Django 3.2.5 on 2021-07-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrom', models.IntegerField()),
                ('pos', models.IntegerField()),
                ('rsid', models.CharField(max_length=1024)),
                ('ref', models.CharField(max_length=1024)),
                ('alt', models.CharField(max_length=1024)),
                ('info', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddIndex(
            model_name='genome',
            index=models.Index(fields=['rsid'], name='genomes_gen_rsid_1944d3_idx'),
        ),
        migrations.AddIndex(
            model_name='genome',
            index=models.Index(fields=['chrom', 'pos'], name='genomes_gen_chrom_4c4728_idx'),
        ),
    ]
